### ISSUE TITLE
Requires local IP to start with 192.168.0.

### ISSUE THREAD

**Issue by darrenhinderer** [epinheiro/EftAiOS-fanGame#3]
I'm on a LAN that I don't control that uses 192.168.1.* so it won't let me setup the game server.

I'm fairly certain other valid LAN addresses can use 10.0.0.* as well.

**Comment by epinheiro** [comment]
Hello there, Darren
I'm not sure if I understand the problem you are facing, can you try to explain it further?
Is the IP provided by the server (ship) screen not reachable by the clients (passenger)? 
![image](https://user-images.githubusercontent.com/12722012/170134851-ae143078-8398-472b-ba29-884ad2772cff.png)

If this is the case, the IP shown is the machine's IP (you can verify with **ipconfig** command in the **cmd** as "IPv4 address" in your relevant network). When you start the game, did you give network access permission to the application in the firewall?

If I misread the issue, please let's talk to reach a possible solution.

**Comment by darrenhinderer** [comment]
ya I was using ipconfig to see my IP and it was 192.168.1.36 or something like that. The key part being the 192.168.1 not 192.168.0

When I launched the app from my phone or laptop it would not display the IP like it does in your screenshot above.

Then I saw in the code that it was specifically only allowing IPs that used 192.168.0

When I got home yesterday from traveling I tested the app on my home network that uses 192.168.0. and the IP address showed up in the app as expected.

**Comment by epinheiro** [comment]
Hello there, [darrenhinderer](https://github.com/darrenhinderer)!
Sorry for the delay but I finally made this code update and uploaded the Android and Windows new versions on the itch page https://epinheiro.itch.io/escape-from-the-aliens-in-outer-space-fan-game
Can you please verify if this alteration solves your issue regarding the game connection?

**Comment by darrenhinderer** [comment]
Yes, it is working! I just tested it out on my work network wifi that use 192.168.96.* and the IP is showing up correctly now. Thanks so much.
